# Generated by Django 5.0 on 2023-12-31 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_url_usersurls_url_large_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurls',
            name='url_small',
            field=models.CharField(max_length=50, verbose_name='Сокращенная ссылка'),
        ),
        migrations.AddConstraint(
            model_name='usersurls',
            constraint=models.UniqueConstraint(fields=('user', 'url_small'), name='unique'),
        ),
    ]
