# Generated by Django 5.0 on 2023-12-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_usersurls_url_small_usersurls_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurls',
            name='url_large',
            field=models.URLField(max_length=100, verbose_name='Длинная ссылка'),
        ),
        migrations.AlterField(
            model_name='usersurls',
            name='url_small',
            field=models.CharField(max_length=20, verbose_name='Сокращенная ссылка'),
        ),
    ]
