# Generated by Django 5.0 on 2023-12-31 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_usersurls_url_large_alter_usersurls_url_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurls',
            name='url_large',
            field=models.URLField(validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Длинная ссылка'),
        ),
    ]
