# Generated by Django 5.0 on 2023-12-31 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_usersurls_url_large'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurls',
            name='url_large',
            field=models.URLField(validators=[django.core.validators.MaxLengthValidator(100, message='Значение должно быть не более 100 символов')], verbose_name='Длинная ссылка'),
        ),
    ]
