# Generated by Django 5.0 on 2023-12-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_usersurls_url_large'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurls',
            name='url_large',
            field=models.URLField(max_length=100, verbose_name='Длинная ссылка'),
        ),
    ]
